server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: admin@123
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
user:
  test:
    property: dev-value
info:
  application:
    name: 'user-service'
    description: 'this is Service that using to get information user owner'
    version: '1.0.0'        